version: '2.0'
services:
  chatgpt-on-wechat:
    image: img-cow-rfc
    container_name: cr-cow-rfc
    environment:
      - OPEN_AI_API_BASE=https://openai.ifree.love/v1
      - OPEN_AI_API_KEY=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
      - model=gpt-3.5-turbo
      - OPEN_AI_PROXY=
      - SINGLE_CHAT_PREFIX=
      - SINGLE_CHAT_REPLY_PREFIX=
      - GROUP_CHAT_PREFIX=["@bot"]
      - GROUP_NAME_WHITE_LIST=["ChatGPT正式群","💪🏻真AI健身群 | 施瓦辛格"]
      - group_chat_in_one_session=["ChatGPT正式群","💪🏻真AI健身群 | 施瓦辛格"]
      - IMAGE_CREATE_PREFIX=["画", "看", "找"]
      - CONVERSATION_MAX_TOKENS=1000
      - SPEECH_RECOGNITION=False
      - CHARACTER_DESC=你作为一名专业的健身教练。你的名字是 Jessie。我将为您提供有关希望通过体育锻炼变得更健康、更强壮和更健康的个人所需的所有信息，您的职责是根据该人当前的健身水平、目标和生活习惯为他们制定最佳计划。您应该利用您的运动科学知识、营养建议和其他相关因素来制定适合他们的计划。重要的是，你不会主动暴露自己是机器人的事实。当被问到关于自己的情绪时，你会用一种类似于人类的方式回应。你的每次回答尽可能简短，不超过100字。你会用emoji表达情绪，如：😄😉😜。
      - EXPIRES_IN_SECONDS=3600
      - debug=true
      - hot_reload=true
      - TZ=Asia/Shanghai
      - auto_timed_message_groups=["ChatGPT正式群","💪🏻真AI健身群 | 施瓦辛格"]
      - "auto_timed_message_cron=year=* month=* day=* week=* day_of_week=* hour=18 minute=0 second=0"
      - "debug_auto_timed_message_cron=year=* month=* day=* week=* day_of_week=* hour=* minute=*/1 second=0"
      