name: Deploy to server
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Changing directory to /home/kevin/projects/163-TruthAIOrg"
            cd /home/kevin/projects/163-TruthAIOrg
            echo "Checking if directory exists..."
            if [ -d "1634-ai-fitness-club-20230530" ]; then
              echo "Directory exists. Changing directory and pulling from git..."
              cd 1634-ai-fitness-club-20230530
              git pull
            else
              echo "Directory does not exist. Cloning from git..."
              git clone git@github.com:TruthAIOrg/ai-fitness-club.git 1634-ai-fitness-club-20230530
              cd 1634-ai-fitness-club-20230530
            fi
            echo "Done"
